# Generated by Django 5.2 on 2025-05-02 01:39

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS main_app_ocrusage CASCADE;",
                "DROP TABLE IF EXISTS main_app_translation CASCADE;",
                "DROP TABLE IF EXISTS main_app_profile CASCADE;",
                "DELETE FROM django_migrations WHERE app = 'main_app';"
            ],
            reverse_sql=[]
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('primary_language', models.CharField(blank=True, max_length=30)),
                ('other_languages', models.JSONField(default=list)),
                ('preferred_language', models.CharField(blank=True, max_length=30)),
                ('is_anonymous', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('target_language', models.CharField(max_length=10)),
                ('translation_type', models.CharField(choices=[('typed', 'Typed')], default='typed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
