# Generated by Django 5.2 on 2025-04-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
