# Generated by Django 5.2 on 2025-05-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default-avatar.png', null=True, upload_to='profile_photos/'),
        ),
    ]
