# Generated by Django 5.2 on 2025-05-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_anonymous',
            field=models.BooleanField(null=True, blank=True),
        ),
    ]
