# Generated by Django 5.2 on 2025-05-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_fix_translation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translation_type',
            field=models.CharField(
                max_length=10,
                choices=[('typed', 'Typed'), ('ocr', 'OCR')],
                default='typed',
            ),
        ),
    ]
