# Generated by Django 5.2 on 2025-05-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_null_user_from_translation'),
    ]

    operations = [
        migrations.RunSQL(
            # First check if request_type exists, if it does, rename it to translation_type
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_name = 'main_app_translation' 
                    AND column_name = 'request_type'
                ) THEN
                    ALTER TABLE main_app_translation RENAME COLUMN request_type TO translation_type;
                ELSIF NOT EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_name = 'main_app_translation' 
                    AND column_name = 'translation_type'
                ) THEN
                    ALTER TABLE main_app_translation ADD COLUMN translation_type character varying(10) NOT NULL DEFAULT 'typed';
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_name = 'main_app_translation' 
                    AND column_name = 'translation_type'
                ) THEN
                    ALTER TABLE main_app_translation RENAME COLUMN translation_type TO request_type;
                END IF;
            END $$;
            """
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_anonymous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_languages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='translation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation_type',
            field=models.CharField(choices=[('typed', 'Typed')], default='typed', max_length=10),
        ),
        migrations.DeleteModel(
            name='OCRUsage',
        ),
    ]
