# Generated by Django 5.2 on 2025-05-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_null_user_from_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_anonymous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_languages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='translation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation_type',
            field=models.CharField(choices=[('typed', 'Typed')], default='typed', max_length=10),
        ),
        migrations.DeleteModel(
            name='OCRUsage',
        ),
    ]
