# Generated by Django 5.2 on 2025-05-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_fix_request_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='request_type',
            new_name='translation_type',
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation_type',
            field=models.CharField(choices=[('typed', 'Typed')], default='typed', max_length=10),
        ),
    ]
