from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_sync_migration_state'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TABLE IF EXISTS main_app_translation;
            CREATE TABLE main_app_translation (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                original_text text NOT NULL,
                translated_text text NOT NULL,
                target_language character varying(10) NOT NULL,
                created_at timestamp with time zone NOT NULL,
                user_id integer NOT NULL,
                translation_type character varying(10) NOT NULL,
                CONSTRAINT main_app_translation_pkey PRIMARY KEY (id),
                CONSTRAINT main_app_translation_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
            );
            CREATE INDEX main_app_translation_user_id_9ed19f7d ON main_app_translation USING btree (user_id);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS main_app_translation;
            """
        ),
    ] 