# Generated by Django 5.2 on 2025-04-22 03:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocr', '0004_delete_ocrtranslate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('target_language', models.CharField(max_length=10)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_tests', to='ocr.ocr')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
