# Generated by Django 5.2 on 2025-04-20 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_alter_ocrtest_options_delete_translatortest'),
        ('translator', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='translationtest',
            name='ocr_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_tests', to='ocr.ocrtest'),
        ),
    ]
