# Generated by Django 5.2 on 2025-04-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_alter_ocrtest_created_at_alter_ocrtest_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrtest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ocr_tests/'),
        ),
        migrations.CreateModel(
            name='TranslatorTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(max_length=10)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ocr_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_tests', to='ocr.ocrtest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
