# Generated by Django 5.2 on 2025-04-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_ocrtranslate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrtranslate',
            name='image',
        ),
    ]
