# Generated by Django 5.2 on 2025-04-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_remove_ocrtranslate_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OCRTranslate',
        ),
    ]
