# Generated by Django 4.1.13 on 2025-04-20 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_alter_ocrtest_image_translatortest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrtest',
            options={},
        ),
        migrations.RemoveField(
            model_name='ocrtest',
            name='image',
        ),
        migrations.AlterField(
            model_name='ocrtest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ocrtest',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TranslatorTest',
        ),
    ]
