# Generated by Django 4.1.13 on 2025-04-20 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_alter_ocrtest_options_remove_ocrtest_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatorTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(max_length=10)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocr_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.ocrtest')),
            ],
        ),
    ]
