# Generated by Django 5.2 on 2025-04-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_translatortest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslatorTest',
        ),
    ]
