# Generated by Django 5.2 on 2025-04-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_translatortest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='TranslatorTest',
        ),
    ]
