# Generated by Django 4.1.13 on 2025-04-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_ocrtranslationtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OCRTranslationTest',
        ),
    ]
